sudo: required
services:
   - docker

before_install:
    - docker build -t priest20/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true priest20/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-434341234769"
    bucket_path: "docker"
    on:
       branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"

   